-- 코드를 작성해주세요
SELECT SUM(C.SCORE) AS SCORE
, B.EMP_NO
, B.EMP_NAME
, B.POSITION
, B.EMAIL
FROM HR_DEPARTMENT AS A
JOIN HR_EMPLOYEES AS B
ON A.DEPT_ID = B.DEPT_ID
JOIN HR_GRADE AS C
ON B.EMP_NO = C.EMP_NO
GROUP BY
    B.EMP_NO, B.EMP_NAME, B.POSITION, B.EMAIL -- GROUP BY는 집계 함수(SUM, COUNT 등)와 함께 사용될 때, SELECT 절에 있는 집계 함수를 제외한 모든 컬럼을 포함
ORDER BY SCORE DESC
LIMIT 1